apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-active
  namespace: basic-frontend
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
  selector:
    app: nodejs-app

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-preview
  namespace: basic-frontend
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
  selector:
    app: nodejs-app
