apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nodejs-app
  namespace: basic-frontend
  annotations:
    pref.argocd.argoproj.io/default-view: pods
    pref.argocd.argoproj.io/default-pod-sort: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: patiltejal40/github-actions-frontend:20240917055258
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
  strategy:
    blueGreen:
      activeService: nodejs-app-active
      previewService: nodejs-app-preview
      autoPromotionEnabled: false
