# Default values for spring-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: basic-frontend
image:
  repository: patiltejal40/github-actions-frontend
  tag: "20240917055258"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
livenessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
